In [ ]:
#array aleatorio de 100 elementos

import numpy as np

random1=np.random.randint(0,500,size=(10,10))
mediana=np.median(random1)
print("Array random:\n",random1)
print("Mediana del array:",mediana)

Array random:
 [[483 137 120 476 480 375 409 388 436 190]
 [161 407 144 210 296 247 492 387 211  92]
 [263  78 288 300 298  35 173 219 392 385]
 [ 59 494 446  60 493  72 466 100 236 174]
 [ 62 209 109 336 130 234 162  92 120 384]
 [163  84 121 481 294  58 445 217 482 202]
 [372 366 114  84 395 441 136 448 372 441]
 [138 288 139 487 353 317 196  92  84 362]
 [468 171 264 453 479  20 443 319 440 124]
 [103 490 379 323 330 334  96  63 148 452]]
Mediana del array: 276.0

In [4]:
#factorización de un número

import numpy as np

random2=np.random.randint(1,11, size=(1,5))
random_num=random2.min()

def factorial(random_num):
  fact=1
  for n in range(1,random_num+1):
    fact*=n
  print(random2)
  print("Número random:",random_num)
  print("El factorial del número es:",fact)

factorial(random_num)

[[6 9 4 5 1]]
Número random: 1
El factorial del número es: 1

In [ ]:
#suma de serie de números

import numpy as np

random3=np.random.randint(0,25, size=(3,3))
min=random3.min()
max=random3.max()

def suma_serie(min,max):
  sum=0
  if min<max:
    for i in range(min,max+1):    
      sum += i 
    for i in range(min,max+1): 
      if i == max:
        print(i,end = '')
      else: print(i,"+ ",end = '')
    print(" =",sum)
  else:
    print("Operación inválida. El primer número de la serie debe ser menor al segundo.")

print("Array random:\n",random3)
print("Número mínimo:",min)
print("Número máximo:",max)
suma_serie(min,max)

Array random:
 [[ 2 15 16]
 [ 3 20 17]
 [19 13 13]]
Número mínimo: 2
Número máximo: 20
2 + 3 + 4 + 5 + 6 + 7 + 8 + 9 + 10 + 11 + 12 + 13 + 14 + 15 + 16 + 17 + 18 + 19 + 20 = 209

In [3]:
#promedio y mediana de los sueldos

import numpy as np
from google.colab import drive
drive.mount('/content/drive')

sueldos_netos = np.loadtxt('/content/drive/MyDrive/Colab Notebooks/Documents/salario_neto.csv', skiprows=1, dtype=int)

print('Promedio de salarios: ', int(sueldos_netos.mean()))
print('Mediana de salarios: ', int(np.median(sueldos_netos)))

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Promedio de salarios:  19309586
Mediana de salarios:  76067